version: "3.8"

services:
  backend:
    build: ./BACKEND
    container_name: backend
    ports:
      - "3000:3000"
    

  app1:
    build: ./APP1
    container_name: app1
    ports:
      - "5000:80"
    depends_on:
      - backend

  app2:
    build: ./APP2
    container_name: app2
    ports:
      - "5001:80"
    depends_on:
      - backend

  